title: Algol Queue
logo_img: 
favicon: 
description: Algorithm Record
global_tags: queue responsive html5
copyright: © muzigae 2022

sass:
    style: compressed

collections:
    category:
        output: true
    authors:
        output: false

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"